version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: bankrest
      POSTGRES_PASSWORD: bankrest
      POSTGRES_DB: bankrest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bank-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bank-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-rest-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8060:8060"
    environment:
      # БД для приложения в контейнере: host = postgres (имя сервиса)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankrest
      SPRING_DATASOURCE_USERNAME: bankrest
      SPRING_DATASOURCE_PASSWORD: bankrest

      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "false"

      JWT_SECRET: "f76295d1b072ce49e8808caf82091dd8b8e2451516996e217d3d7547fd7dae6e"
      JWT_EXPIRATION: "3600000"
      CARD_SECRET: "vOL6szZ0sHYzZJx5XZArG8VUla9viG0BXgiAo7Pooas="

      SERVER_PORT: "8060"

    networks:
      - bank-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  bank-network:
    driver: bridge
