spring:
  application:
    name: BankRest
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    database: postgresql
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:docs/
      static-path-pattern: /docs/**

server:
  port: 8060

auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000

card:
  secretKey: ${CARD_SECRET}

springdoc:
  swagger-ui:
    url: /v3/api-docs.yaml

liquibase:
  change-log: classpath:db/migration/db.changelog-master.yaml
  contexts: development, production
  default-schema: public
  drop-first: false
  enabled: true

