spring:
  datasource:
    url: jdbc:postgresql://prod-db:5432/BankRest
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    contexts: production
    default-schema: public
    enabled: true

server:
  port: 8080

auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000

card:
  secretKey: ${CARD_SECRET}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: false
